### ISSUE TITLE
Konzept

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedWarps#1]
[Lastenheft - RedWarps.txt](https://github.com/RedstoneWorld/RedWarps/files/4639570/Lastenheft.-.RedWarps.txt)

**Comment by Phoenix616** [comment]
Wenn ich das richtig sehe soll das Plugin nur auf einem einzelnen Minecraft Server teleportieren und nicht zwischen anderen Servern im ganzen Bungee?

**Comment by RedstoneFuture** [comment]
Richtig. Ich weiß: Bungee-Warps sehen fortschrittlich aus - sie haben aber auch nachteile ...

Ich möchte mit "/server" zeigen, dass es ein anderer Server ist und dass sie dort auch andere Befehle, Permissions, Welten, einen anderen Lokalchat **und andere Warppunkte haben**, sich die Server-Restarts unterscheiden etc. Die Teleports (/tp) und Homepunkte (/homes) sind bei mir auch nicht serverübergreifend.

Wenn die Spieler mit zuvielen Befehlen zwischen den Servern wechseln können verlieren sie das Gefühl für die Server-Unterscheidung. Das ist gut, wenn man - wie bei großen Servern - alles danach konzeptioniert und eingerichtet hat und unbedingt dieses Feeling eines zusammenhängenden Servers braucht. Weder ist das bei mir technisch der Fall, noch muss ich dieses Feeling erbringen. Im Gegenteil: die technische und ersichtliche Strukturierung zwischen den Servern hilft den Spielern die unterschiedlichen Konzepte zu verstehen. Gerade bei so vielen unterschiedlichen Plugins & Befehlen.

Ein kleiner Nebeneffekt ist auch, dass ich den Warppunkt "Spawn" auf jedem Server einzeln setzen kann. Das funktioniert ganz gut, da die Spieler wissen, dass sie dafür mit "/hs" oder "/server hs" zum Hauptserver zurückkommen. Insbesondere, weil es bei mir in der TAB-Liste steht.

**Comment by RedstoneFuture** [comment]
Wenn du meinst, dass du mit dem Plugin selber was anfangen kannst, können wir aber gerne daraus ein Bungee-Plugin machen und für jeden Befehl eine Art Server-Whitelist zulassen. Der Unterschied zur No-Permission Nachricht ist hier, dass es weiterhin vermittelt:

"_Es gibt diesen Warppunkt auf diesem MC Server nicht. Ich muss den Unter-Server wechseln_."

**Comment by Phoenix616** [comment]
Also selber brauche ich das nicht wirklich, hab dafür ja ne ganze Teleport-Suite mit Clusterfunktion. Hätte aber nen ersten Prototyp (Mit Teleports auf Bukkit Ebene) fertig, bräuchte da nur mal Push-Rechte auf das Repo ;D

**Comment by RedstoneFuture** [comment]
done

**Comment by Phoenix616** [comment]
Builds: https://ci.minebench.de/view/RedstoneWorld/job/RedWarps/

Habs jetzt noch nicht getestet, würde ich morgen oder so machen oder du sagst einfach bescheid wenn du es dir schon anschauen willst und du Fehler bemerkst :)

**Comment by RedstoneFuture** [comment]
Alles klar, danke.
