### ISSUE TITLE
"suggest command" wird mit angezeigt

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedWarps#4]
Hab ich was falsch oder kannst du da was tun? Oder war das so gewollt?

`  setwarp: 'Schreibe: [&7/setwarp <Warp-Name> <ggf. ein oder mehrere Warppunkt-Aliasse>](suggest_command=/setwarp)'`

![2020-06-12_17 04 50](https://user-images.githubusercontent.com/4140635/84517066-04fb3080-accf-11ea-9be6-97f15b0df857.png)

**Comment by Phoenix616** [comment]
Das ist die Beschreibung dafür was passiert wenn man auf den Befehl klickt (um es von automatisch ausgeführten Befehlen oder URLs zu differenzieren). Wenn du da einen anderen Text stehen haben willst einfach den [MineDown syntax](https://github.com/Phoenix616/MineDown#advanced-syntax) nutzen und zB. `hover=Klicke um den Befehl einzuzügen` anhängen.

**Comment by RedstoneFuture** [comment]
Danke.
